<?php

return [
    'bin_path' => env('QEMU_BIN_PATH', '/usr/bin/qemu-system-x86_64'),
    'img_path' => env('QEMU_IMG_PATH', '/usr/bin/qemu-img'),
    'vm_storage' => env('QEMU_VM_STORAGE', '/var/lib/qemu/vms'),
    'iso_storage' => env('QEMU_ISO_STORAGE', '/var/lib/qemu/iso'),
    'iso_directories' => array_filter(array_map('trim', explode(',', env('QEMU_ISO_DIRECTORIES', '/var/lib/qemu/iso,/srv/iso')))),
    'iso_upload_directories' => env('QEMU_ISO_UPLOAD_DIRECTORIES') ? array_filter(array_map('trim', explode(',', env('QEMU_ISO_UPLOAD_DIRECTORIES')))) : null,
    'iso_upload_fallback' => env('QEMU_ISO_UPLOAD_FALLBACK') ?: null,
    'iso_upload_staging' => env('QEMU_ISO_UPLOAD_STAGING') ?: '/var/lib/qemu/iso-staging',
    'boot_media_service_url' => env('BOOT_MEDIA_SERVICE_URL', 'http://127.0.0.1:50052'),
    'vnc_host' => env('VNC_HOST', '127.0.0.1'),
    'vnc_host_for_tokens' => env('VNC_HOST_FOR_TOKENS'),
    'vnc_ws_host' => env('VNC_WS_HOST'),
    'vnc_ws_port' => (int) env('VNC_WS_PORT', 50055),
    'vnc_proxy_via_qemu_control' => (bool) env('VNC_PROXY_VIA_QEMU_CONTROL', true),
    'qmp_socket_dir' => env('QEMU_QMP_SOCKET_DIR', '/var/qemu/qmp'),
    'use_external_qemu' => (bool) env('QEMU_USE_EXTERNAL', true),
    'qemu_control_service_url' => env('QEMU_CONTROL_SERVICE_URL', 'http://127.0.0.1:50054'),
    'boot_media_service_api_key' => env('BOOT_MEDIA_SERVICE_API_KEY'),
    'disable_audio' => (bool) env('QEMU_DISABLE_AUDIO', true),
    'default_architecture' => env('QEMU_DEFAULT_ARCH', 'x86_64'),
    'default_bridge' => env('QEMU_DEFAULT_BRIDGE', 'br0'),
    'architectures' => array_values(array_filter(array_map('trim', explode(',', env('QEMU_TARGET_ARCHES', 'x86_64'))))),
    'binary_map' => [
        'x86_64' => '/usr/bin/qemu-system-x86_64',
        'i386' => '/usr/bin/qemu-system-i386',
        'arm' => '/usr/bin/qemu-system-arm',
        'aarch64' => '/usr/bin/qemu-system-aarch64',
        'riscv64' => '/usr/bin/qemu-system-riscv64',
        'mips' => '/usr/bin/qemu-system-mips',
        'ppc64' => '/usr/bin/qemu-system-ppc64',
        'sparc' => '/usr/bin/qemu-system-sparc64',
    ],
];
